### ISSUE TITLE
using shelf_proxy as fallback handler in shelf_route

### ISSUE THREAD

**Issue by mlesin** [dart-lang/shelf_proxy#2]
I'm trying to use proxy handler as a fallback handler for shelf_route like this:

    Handler staticHandler = proxyHandler("http://localhost:8080/");
    Router rootRouter = router(fallbackHandler: staticHandler);
    handler = const Pipeline()
        .addMiddleware(logRequests())
        .addMiddleware(exceptionHandler())
        .addHandler(rootRouter.handler);

but it says the following:

    Error thrown by handler.
    Bad state: The 'read' method can only be called once on a shelf.Request/shelf.Response object.
    package:shelf/src/message.dart 119:7           Message.read
    package:shelf_proxy/shelf_proxy.dart 47:25     proxyHandler.<fn>
    package:shelf_route/src/route_impl.dart 34:31  _BaseRoute.createHandler.<fn>.<async>

Is that by design or it's a bug?

**Comment by nex3** [comment]
This is caused by dart-lang/shelf#49.
